# vim: ft=tmux
set -g mode-style "fg=#eee8d5,bg=#073642"

set -g message-style "fg=#eee8d5,bg=#073642"
set -g message-command-style "fg=#eee8d5,bg=#073642"

set -g pane-border-style "fg=#839496"
set -g pane-active-border-style "fg=#98C379"

set -g status "on"
set -g status-interval 1
set -g status-justify "left"

set -g status-style "fg=#586e75,bg=#073642"

# set -g status-bg "#002b36"
set -g status-bg "#3D484E"

set -g status-left-length "100"
set -g status-right-length "100"

set -g status-left-style NONE
set -g status-right-style NONE

set -g status-left "#[fg=#073642,bg=#93a1a1,bold] #S #[fg=#93a1a1,bg=#3D484E,nobold,nounderscore,noitalics]#[fg=#3D484E,bg=#c9c9c9,]#[fg=#15161E,bg=#c9c9c9,bold] #(whoami) #[fg=#c9c9c9,bg=#3D484E]"
set -g status-right "#[fg=#586e75,bg=#3D484E,nobold,nounderscore,noitalics]#[fg=#93a1a1,bg=#586e75]#[fg=#657b83,bg=#586e75,nobold,nounderscore,noitalics]#[fg=#93a1a1,bg=#657b83]#[fg=#93a1a1,bg=#657b83,nobold,nounderscore,noitalics]#[fg=#15161E,bg=#93a1a1,bold] #(date +\%R)  #(date +\%a) #(date +\%d) #(date +\%b)   "

setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#839496,bg=#3D484E"
# setw -g window-status-format '#[fg=#3D484E,bg=#3D484E]#[default] #I  #{b:window_name} #[fg=#3D484E,bg=#3D484E,nobold,nounderscore,noitalics]'
setw -g window-status-format '#[fg=#3D484E,bg=#697681]#[fg=#15161e,bg=#697681] #I #[fg=#697681,bg=#56626A]#[fg=#15161e] #{b:window_name} #[fg=#56626A,bg=#3D484E,nobold]'
# setw -g window-status-current-format '#[fg=#3D484E,bg=#98C379]#[fg=#15161e,bg=#98C379] #I #[fg=#98C379,bg=#c9c9c9]#[fg=#15161e] #{b:window_name} #[fg=#c9c9c9,bg=#3D484E,nobold]'
setw -g window-status-current-format '#[fg=#3D484E,bg=#98C379]#[fg=#15161e,bg=#98C379] #I #[fg=#98C379,bg=#98C379]#[fg=#15161e]#[fg=#15161e] #{b:window_name} #[fg=#98C379,bg=#3D484E,nobold]'
